### ISSUE TITLE
您好 在QT4.7和QT5中都出现编译错误

### ISSUE THREAD

**Issue by hanzhenlll** [justdoit-2017/softkeyboard#1]
抱歉，最近没登陆过github，也不是很熟悉github的操作，不小心就把你的问题给删了，不知道你的问题解决了没？
我看编译错误提示是重定义问题，pro文件中
SOURCES +=
main.cpp
moc_softkeyboard.cpp
softkeyboard.cpp
多加了个moc_softkeyboard.cpp。

**Comment by justdoit-2017** [comment]
抱歉，这段时间没登过github，不知道你的问题解决了没？
我看编译错误提示是重定义问题，pro文件中
SOURCES +=
main.cpp
moc_softkeyboard.cpp
softkeyboard.cpp
多加了个moc_softkeyboard.cpp。

**Comment by hanzhenlll** [comment]
感谢回复，我下载了新版本,界面很舒服，win下在QT5上编译通过可以正常运行了。
支持全拼 双拼 联想 不错，非常棒的例子,感谢 ~~
